# Generated by Django 4.1 on 2023-12-08 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.TextField(db_index=True, verbose_name='name of the experiment')),
                ('description', models.TextField(db_index=True, verbose_name='description of the experiment')),
                ('agent_rl_playing_url', models.TextField(blank=True, db_index=True, null=True, verbose_name='url of the rl agent in action after fine tuning')),
                ('agent_immitation_playing_url', models.TextField(blank=True, db_index=True, null=True, verbose_name='url of the agent in action after immitation')),
                ('training_data_url', models.TextField(blank=True, db_index=True, null=True, verbose_name='url of the training data')),
                ('training_statistics_graph_url', models.TextField(blank=True, db_index=True, null=True, verbose_name='url of the training statistics graph which depeicts the avg score per round')),
                ('rl_human_fusion_score', models.FloatField(blank=True, db_index=True, null=True, verbose_name='rl score after averaging over ten games')),
                ('immitation_score', models.FloatField(blank=True, db_index=True, null=True, verbose_name='immitation score after averaging over ten games')),
                ('is_training_data_uploaded', models.BooleanField(default=False, verbose_name='is training data uploaded')),
                ('is_done_training', models.BooleanField(default=False, verbose_name='is done training')),
            ],
        ),
    ]
