# Generated by Django 4.1 on 2023-12-03 05:40

from django.db import migrations, models
import human_prefs.models


class Migration(migrations.Migration):

    dependencies = [
        ('human_prefs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='response_kind',
            field=models.TextField(db_index=True, validators=[human_prefs.models.validate_inclusion_of_response_kind], verbose_name='kind of response from the tasker. may be left, right, tie, or abstain'),
        ),
    ]
